### ISSUE TITLE
Installation on Python 3.9

### ISSUE THREAD

**Issue by amotl** [ambianic/peerjs-python#48]
Hi Ivelin,

as outlined within #46, there are no binary wheels for PyAV on Python 3.9 yet, see [1]. @Odianosen25 observed the same within https://github.com/PyAV-Org/PyAV/issues/697. So, we probably should add a friendly question at [2], asking whether building and uploading binary wheels for Python 3.9 to PyPI would be possible.

Otherwise, people installing `peerjs-python` will need the complete compiler toolchain plus appropriate header files of ffmpeg and friends on their machines which might not be appropriate for many occasions as the additional build cycle will a) waste resources and b) might take quite a while on lower-end machines like the RaspberryPi or even less powerful ARM-based SBCs.

With kind regards,
Andreas.

[1] https://pypi.org/project/av/#files
[2] https://github.com/PyAV-Org/PyAV/issues

EDIT: I just recognized there are no PyAV wheels for ARM on [1] yet, so please forget about my last comment. However, it might make sense to also ask for them as I discovered that [ambianic-box](https://github.com/ambianic/ambianic-box) is actually ARM-based, right?

I found that [PyAV already uses `pibuildwheel`](https://github.com/PyAV-Org/PyAV/blob/v8.0.2/.github/workflows/tests.yml#L231-L233) and adding building for ARM into the mix will be possible. https://github.com/PyTables/PyTables/issues/823 has many interesting details about this topic.

**Comment by ivelin** [comment]
Hi Andreas,

Thank you for investigating further.

Maybe I misunderstood #47 . I thought Ubuntu 20.4 resolves the ffmpeg binary wheel issue and there is no need to build ffmpeg from source if python 3.9 is running on Ubuntu 20.4 or above. Is that not the case?

Maybe we can clarify in the docs that peerjs-python requires Ubuntu 20.4 or later to run within Python 3.9 without building ffmpeg from source.

I completely support opening a friendly request with [2].

Ivelin

**Comment by amotl** [comment]
Hi Ivelin,

> Maybe I misunderstood #47. I thought Ubuntu 20.4 resolves the ffmpeg binary wheel issue and there is no need to build ffmpeg from source if python 3.9 is running on Ubuntu 20.4 or above. Is that not the case?

That's partly true. While `ffmpeg` does not have to be compiled, the PyAV binding still does. When binary wheels of PyAV for Python 3.9 are provided, this step will not be required on downstream machines.

> Maybe we can clarify in the docs that peerjs-python requires Ubuntu 20.4 or later to run within Python 3.9.

That will make sense.

> I completely support opening a friendly request with [2].

I've just created https://github.com/PyAV-Org/PyAV/issues/734.

> I apologize for not being able to dig deeper into this specific issue at the moment. Tackling a number of other immediate project issues.

Good luck!

With kind regards,
Andreas.

**Comment by ivelin** [comment]
@amotl 

Just following up on the status of this issue. Can we close it or there is something else specific we need to do on our end?

**Comment by amotl** [comment]
Hi Ivelin,

I see that the release of PyAV 8.0.3 [1], published on Jan 23, 2021, now offers binary wheels for Python 3.9. So, I believe closing this issue is fine.

With kind regards,
Andreas.

[1] https://pypi.org/project/av/#files

**Comment by amotl** [comment]
Proof:
```sh
virtualenv .venv --python=python3.9
source .venv/bin/activate
pip install peerjs
[...]
Collecting av~=8.0.0
  Downloading av-8.0.3-cp39-cp39-macosx_10_9_x86_64.whl (21.5 MB)
```

**Comment by ivelin** [comment]
Great. Thank you for verifying. I guess we can now remove the Python 3.9 note from the README doc?
