### ISSUE TITLE
Implementing Media Connection Handling for Call & Answer

### ISSUE THREAD

**Issue by mmhy2003** [ambianic/peerjs-python#58]
Hello, I tried your library and it works great with exchanging data between peers.
But, I'm also interested in exchanging streams between peers.

I'm looking forward to seeing you implement this part.

Thanks in advance,

**Comment by ivelin** [comment]
Thank you, @mmhy2003 . 

Can you please share what type of problem peerfetch solves for you?

By streams, do you mean datachannel streams or media? Can you please elaborate.

**Comment by mmhy2003** [comment]
Thanks @ivelin for your reply.

I'm currently working on a small personal project.

Simply, I'm building an audio call application using peerjs where I want the server (In my case Python) to join as a peer between 2 clients and act as a translator and transcriber by processing audio streams.

I noticed that your library has the datachannel part from peerjs implemented but not the call & answer media streams part yet, So, I was wondering will it be available in the near future?

Thanks in advance,

**Comment by ivelin** [comment]
@mmhy2003 thank you for sharing. No immediate plans for media API, but I'd be happy to review PRs. 
Happy Holidays!
