### ISSUE TITLE
ValueError: mutable default <class 'aiortc.rtcconfiguration.RTCConfiguration'> for field config is not allowed: use default_factory

### ISSUE THREAD

**Issue by espeed** [ambianic/peerjs-python#66]
from dataclasses import dataclass, field

config: Any = field(default_factory=lambda: util.defaultConfig)

Fixes 

ValueError: mutable default <class 'aiortc.rtcconfiguration.RTCConfiguration'> for field config is not allowed: use default_factory

https://github.com/ambianic/peerjs-python/blob/master/src/peerjs/peer.py#L52

**Comment by ivelin** [comment]
Thank you, @espeed 

Which version of aiortc does this change apply to? 

Would you mind submitting a PR with some additional context on aiortc version dependency?

**Comment by espeed** [comment]
>>> aiortc.__version__
'1.6.0'
>>> av.__version__
'11.0.0'

**Comment by espeed** [comment]
PR submitted.

**Comment by espeed** [comment]
Python 3.12.1

**Comment by ivelin** [comment]
Great, thank you! Will merge.
